apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-app
  namespace: shinebayar-g
  labels:
    app: flask-app
    team: alpha-1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75 # Calculate Requests value
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
